services:
  db: # Defines the 'db' service for MySQL database
    image: mysql:8.0                # Uses the MySQL 8.0 Docker image
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:                    # Sets environment variables for the database configuration
      - MYSQL_DATABASE=qfrdb        # Specifies the name of the database
      - MYSQL_PASSWORD=pass123      # Sets the password for the MySQL user
      - MYSQL_ROOT_PASSWORD=pass123 # Sets the root password for MySQL
    networks:
      - qfrNetwork                  # Connects the service to the 'qfrNetwork' network
    ports:
      - 3307:3306                   # Maps the container's port 3306 to the host's port 3307

  api: # Defines the 'api' service for the backend API
    volumes:
      - ./backend:/app
      - /srv/app/node_modules
    build:                          # Builds the backend API using the provided Dockerfile
      context: ./backend            # Specifies the build context directory for the backend
      dockerfile: Dockerfile        # Specifies the Dockerfile to use for building the backend
    ports:
      - 3000:3000                   # Maps the container's port 3000 to the host's port 3000
    networks:
      - qfrNetwork                  # Connects the service to the 'qfrNetwork' network
    depends_on:
      - db                          # Specifies that the 'api' service depends on the 'db' service

  frontend:
    image: node:alpine
    volumes:
      - ./frontend:/srv/app
      - /srv/app/node_modules
    entrypoint: /bin/sh
    ports:
      - 3001:3000                   # Maps the container's port 3000 to the host's port 3001
    tty: true
    networks:
      - qfrNetwork

  mosquitto:
    image: eclipse-mosquitto
    # hostname: mosquitto
    # container_name: mosquitto
    # network_mode: "host"
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      # - ./mosquitto:/etc/mosquitto
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - qfrNetwork

networks:
  qfrNetwork:                       # Defines the 'qfrNetwork' network
    driver: bridge                  # Specifies the network driver as 'bridge'
